#!/usr/bin/env python3
import minimalmodbus
import serial

BATTERY_TYPE = 0
BATTERY_CAPACITY = 130
BATTERY_TEMPERATURE_COMPENSATION_COEFFICIENT = 300
BATTERY_OVERVOLTAGE_DISCONNECT_VOLTAGE = 5840 #5840 recommended (=3.65V/cell)
BATTERY_CHARGING_LIMIT_VOLTAGE = 5760 #5760 recommended (=3.6V/cell)
BATTERY_OVERVOLTAGE_RECONNECT_VOLTAGE = 5616 #(=3.51V/cell)
BATTERY_EQUALIZATION_VOLTAGE = 5520 #5440 recommended (=3.4V/cell)
BATTERY_BOOST_VOLTAGE = 5520 #5440 recommended (=3.4V/cell)
BATTERY_FLOAT_VOLTAGE = 5360 #5392 recommended (=3.37V/cell)
BATTERY_BOOST_RECONNECT_VOLTAGE = 5280 #(=3.3V/cell)
BATTERY_LOW_VOLTAGE_RECONNECT_VOLTAGE = 5120
BATTERY_UNDERVOLTAGE_RECOVERY_VOLTAGE = 4880
BATTERY_UNDERVOLTAGE = 4800
BATTERY_LOW_VOLTAGE_DISCONNECT_VOLTAGE = 4440
BATTERY_DISCHARGE_LIMIT_VOLTAGE = 4400
BATTERY_EQUALIZATION_DURATION=0
BATTERY_BOOST_DURATION=60


print("Opening connection...")
instrument = minimalmodbus.Instrument("/dev/ttyACM0", 1)
instrument.serial.baudrate = 115200
instrument.serial.bytesize = 8
instrument.serial.parity = serial.PARITY_NONE
instrument.serial.stopbits = 1
instrument.serial.timeout = 1
instrument.mode = minimalmodbus.MODE_RTU
instrument.clear_buffers_before_each_transaction = True

print("Writing parameters...")
instrument.write_registers(0x9000, values=[
 BATTERY_TYPE,
 BATTERY_CAPACITY,
 BATTERY_TEMPERATURE_COMPENSATION_COEFFICIENT,
 BATTERY_OVERVOLTAGE_DISCONNECT_VOLTAGE,
 BATTERY_CHARGING_LIMIT_VOLTAGE,
 BATTERY_OVERVOLTAGE_RECONNECT_VOLTAGE,
 BATTERY_EQUALIZATION_VOLTAGE,
 BATTERY_BOOST_VOLTAGE,
 BATTERY_FLOAT_VOLTAGE,
 BATTERY_BOOST_RECONNECT_VOLTAGE,
 BATTERY_LOW_VOLTAGE_RECONNECT_VOLTAGE,
 BATTERY_UNDERVOLTAGE_RECOVERY_VOLTAGE,
 BATTERY_UNDERVOLTAGE,
 BATTERY_LOW_VOLTAGE_DISCONNECT_VOLTAGE,
 BATTERY_DISCHARGE_LIMIT_VOLTAGE
])
instrument.write_register(0x906B, BATTERY_EQUALIZATION_DURATION, 0, 16, False)
instrument.write_register(0x906C, BATTERY_BOOST_DURATION, 0, 16, False)

print("Done")